# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencode < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/sst/opencode"
  version "1.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sst/opencode/releases/download/v1.0.6/opencode-darwin-x64.zip"
      sha256 "132c19a88da0417453263a7ce6aa7669b920e101078760b56851c55138b7e581"

      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sst/opencode/releases/download/v1.0.6/opencode-darwin-arm64.zip"
      sha256 "c9d02a474ed2c511808366db096b19fe40eb526211ab0027e882ab0d13618a1b"

      def install
        bin.install "opencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sst/opencode/releases/download/v1.0.6/opencode-linux-x64.zip"
      sha256 "6dc0973e96167c005774415616a2da79424abdca8481c97482d3bdd2240521a9"
      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sst/opencode/releases/download/v1.0.6/opencode-linux-arm64.zip"
      sha256 "4d5c382101ddb7eccba14ea87aa11bdf1e4c304a9fc4d6078891a8c2aa0f64fb"
      def install
        bin.install "opencode"
      end
    end
  end
end

