# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencode < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/sst/opencode"
  version "1.0.205"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sst/opencode/releases/download/v1.0.205/opencode-darwin-x64.zip"
      sha256 "c88898b6e682d97abe75fde44e969e9c7bc3c36a75a19b5ca1b13858e92d06aa"

      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sst/opencode/releases/download/v1.0.205/opencode-darwin-arm64.zip"
      sha256 "c3799b28882a975f33aee56cd26821d7c01442b07aadd927697ed74586894e04"

      def install
        bin.install "opencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sst/opencode/releases/download/v1.0.205/opencode-linux-x64.tar.gz"
      sha256 "ce0af6e5219da0d22c5587e1f712c2776441e5d2844e71494883c357f573b377"
      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sst/opencode/releases/download/v1.0.205/opencode-linux-arm64.tar.gz"
      sha256 "a2032b585d980bd305b4e9864ee059dc63ed7f97ec07866a5d8fc20b8055636e"
      def install
        bin.install "opencode"
      end
    end
  end
end

